# 服务属性配置
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # registerWithEureka：false and fetchRegistry：false, 表明自己是一个eureka server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # 服务的注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server